import {CameraDevice,
    PropertyName,
    CommandName,
    BaseStationProperties,
    GenericDeviceProperties,
    DeviceBatteryProperty,
    DeviceBatteryTempProperty,
    DeviceFloodlightLightProperty,
    DevicePictureProperty,
    DevicePictureUrlProperty,
    DeviceStateProperty,
    DeviceNightvisionProperty,
    DeviceChimeIndoorBatteryDoorbellProperty,
    DeviceMicrophoneProperty,
    DeviceAntitheftDetectionProperty,
    DeviceFloodlightLightSettingsEnableProperty,
    DeviceRecordingEndClipMotionStopsProperty,
    DeviceSpeakerVolumeProperty,
    DeviceSnoozeProperty,
    DeviceDetectionStatisticsWorkingDaysProperty,
    DeviceNotificationTypeProperty,
    DeviceDetectionStatisticsDetectedEventsProperty,
    DevicePowerWorkingModeProperty,
    DeviceChimeHomebaseRingtoneVolumeBatteryDoorbellProperty,
    DeviceImageMirroredProperty,
    DeviceFloodlightLightSettingsMotionTriggeredProperty,
    DeviceDetectionStatisticsRecordedEventsProperty,
    DeviceStatusLedProperty,
    DevicePowerSourceProperty,
    DeviceNotificationRingProperty,
    DeviceContinuousRecordingTypeProperty,
    DeviceRecordingClipLengthProperty,
    DeviceNotificationPersonS350Property,
    DeviceNotificationAllOtherMotionS350Property,
    DeviceContinuousRecordingProperty,
    DeviceRingtoneVolumeBatteryDoorbellProperty,
    DeviceChargingStatusProperty,
    DeviceVideoTypeStoreToNASProperty,
    DeviceMotionDetectionIndoorSoloFloodProperty,
    DeviceRTSPStreamProperty,
    DeviceRTSPStreamUrlProperty,
    DeviceAudioRecordingProperty,
    DeviceChimeHomebaseBatteryDoorbellProperty,
    DeviceDualCamWatchViewModeProperty,
    DeviceSpeakerProperty,
    DeviceMotionDetectionTypeProperty,
    DeviceWDRProperty,
    DeviceWatermarkProperty,
    DeviceWifiRSSIProperty,
    DeviceRecordingRetriggerIntervalProperty,
    DeviceMotionDetectionSensitivityCamera2Property,
    DeviceChimeHomebaseRingtoneTypeBatteryDoorbellProperty,
    DevicePersonNameProperty,
    DeviceFloodlightLightSettingsBrightnessMotionProperty,
    DeviceFloodlightLightSettingsBrightnessManualProperty,
    DeviceNotificationPetS350Property,
    StationLanIpAddressStandaloneProperty,
    StationMacAddressProperty,
    StationGuardModeProperty,
    StationCurrentModeProperty,
    StationTimeFormatProperty,
    StationAlarmProperty,
    StationAlarmTypeProperty,
    StationNotificationSwitchModeScheduleProperty,
    StationNotificationSwitchModeAppProperty,
    StationSdStatusProperty,
    StationSdCapacityProperty,
    StationSdAvailableCapacityProperty,
    } from '../../types';
import {
    DeviceMotionHB3DetectionTypeHumanProperty,
    DeviceMotionHB3DetectionTypeVehicleProperty,
    DeviceMotionHB3DetectionTypeAllOtherMotionsProperty,
    DeviceMotionHB3DetectionTypePetProperty,
} from '../station/home_base_3'

export const EufyCamC35: CameraDevice = {
    modelName: 'EufyCamC35',
    deviceType: 10035,
    prefixSerialNumber: 'T8110',
    firmwareVersion: '1.5.0',
    deviceProperties: {
        ...GenericDeviceProperties,
        [PropertyName.DeviceLight]: DeviceFloodlightLightProperty,
        [PropertyName.DevicePicture]: DevicePictureProperty,
        [PropertyName.DevicePictureUrl]: DevicePictureUrlProperty,
        [PropertyName.DeviceState]: DeviceStateProperty,
        [PropertyName.DeviceNightvision]: DeviceNightvisionProperty,
        [PropertyName.DeviceChimeIndoor]: DeviceChimeIndoorBatteryDoorbellProperty,
        [PropertyName.DeviceMicrophone]: DeviceMicrophoneProperty,
        [PropertyName.DeviceAntitheftDetection]: DeviceAntitheftDetectionProperty,
        [PropertyName.DeviceLightSettingsEnable]: DeviceFloodlightLightSettingsEnableProperty,
        [PropertyName.DeviceRecordingEndClipMotionStops]: DeviceRecordingEndClipMotionStopsProperty,
        [PropertyName.DeviceSpeakerVolume]: DeviceSpeakerVolumeProperty,
        [PropertyName.DeviceSnooze]: DeviceSnoozeProperty,
        [PropertyName.DeviceDetectionStatisticsWorkingDays]: DeviceDetectionStatisticsWorkingDaysProperty,
        [PropertyName.DeviceNotificationType]: DeviceNotificationTypeProperty,
        [PropertyName.DeviceDetectionStatisticsDetectedEvents]: DeviceDetectionStatisticsDetectedEventsProperty,
        [PropertyName.DevicePowerWorkingMode]: DevicePowerWorkingModeProperty,
        [PropertyName.DeviceChimeHomebaseRingtoneVolume]: DeviceChimeHomebaseRingtoneVolumeBatteryDoorbellProperty,
        [PropertyName.DeviceImageMirrored]: DeviceImageMirroredProperty,
        [PropertyName.DeviceLightSettingsMotionTriggered]: DeviceFloodlightLightSettingsMotionTriggeredProperty,
        [PropertyName.DeviceDetectionStatisticsRecordedEvents]: DeviceDetectionStatisticsRecordedEventsProperty,
        [PropertyName.DeviceStatusLed]: DeviceStatusLedProperty,
        [PropertyName.DevicePowerSource]: DevicePowerSourceProperty,
        [PropertyName.DeviceNotificationRing]: DeviceNotificationRingProperty,
        [PropertyName.DeviceContinuousRecordingType]: DeviceContinuousRecordingTypeProperty,
        [PropertyName.DeviceMotionDetectionTypeHuman]: DeviceMotionHB3DetectionTypeHumanProperty,
        [PropertyName.DeviceMotionDetectionTypeVehicle]: DeviceMotionHB3DetectionTypeVehicleProperty,
        [PropertyName.DeviceMotionDetectionTypeAllOtherMotions]: DeviceMotionHB3DetectionTypeAllOtherMotionsProperty,
        [PropertyName.DeviceMotionDetectionTypePet]: DeviceMotionHB3DetectionTypePetProperty,
        [PropertyName.DeviceRecordingClipLength]: DeviceRecordingClipLengthProperty,
        [PropertyName.DeviceNotificationPerson]: DeviceNotificationPersonS350Property,
        [PropertyName.DeviceNotificationPet]: DeviceNotificationPetS350Property,
        [PropertyName.DeviceNotificationAllOtherMotion]: DeviceNotificationAllOtherMotionS350Property,
        [PropertyName.DeviceBatteryTemp]: DeviceBatteryTempProperty,
        [PropertyName.DeviceContinuousRecording]: DeviceContinuousRecordingProperty,
        //[PropertyName.DeviceVideoStreamingQuality]: DeviceVideoStreamingQualitySoloProperty,
        [PropertyName.DeviceRingtoneVolume]: DeviceRingtoneVolumeBatteryDoorbellProperty,
        //[PropertyName.DeviceMotionDetectionSensitivity]: DeviceMotionDetectionSensitivityIndoorProperty,
        [PropertyName.DeviceChargingStatus]: DeviceChargingStatusProperty,
        [PropertyName.DeviceVideoTypeStoreToNAS]: DeviceVideoTypeStoreToNASProperty,
        [PropertyName.DeviceMotionDetection]: DeviceMotionDetectionIndoorSoloFloodProperty,
        [PropertyName.DeviceRTSPStream]: DeviceRTSPStreamProperty,
        [PropertyName.DeviceRTSPStreamUrl]: DeviceRTSPStreamUrlProperty,
        [PropertyName.DeviceAudioRecording]: DeviceAudioRecordingProperty,
        //[PropertyName.DeviceVideoStreamingQuality]: DeviceVideoStreamingQualityProperty,
        //[PropertyName.DeviceVideoRecordingQuality]: DeviceVideoStreamingQualityCameraProperty,
        [PropertyName.DeviceChimeHomebase]: DeviceChimeHomebaseBatteryDoorbellProperty,
        [PropertyName.DeviceDualCamWatchViewMode]: DeviceDualCamWatchViewModeProperty,
        [PropertyName.DeviceSpeaker]: DeviceSpeakerProperty,
        [PropertyName.DeviceBattery]: DeviceBatteryProperty,
        [PropertyName.DeviceMotionDetectionType]: DeviceMotionDetectionTypeProperty,
        [PropertyName.DeviceVideoWDR]: DeviceWDRProperty,
        [PropertyName.DeviceWatermark]: DeviceWatermarkProperty,
        [PropertyName.DeviceWifiRSSI]: DeviceWifiRSSIProperty,
        [PropertyName.DeviceRecordingRetriggerInterval]: DeviceRecordingRetriggerIntervalProperty,
        [PropertyName.DeviceMotionDetectionSensitivity]: DeviceMotionDetectionSensitivityCamera2Property,
        [PropertyName.DeviceChimeHomebaseRingtoneType]: DeviceChimeHomebaseRingtoneTypeBatteryDoorbellProperty,
        [PropertyName.DevicePersonName]: DevicePersonNameProperty,
        [PropertyName.DeviceLightSettingsBrightnessMotion]: DeviceFloodlightLightSettingsBrightnessMotionProperty,
        [PropertyName.DeviceLightSettingsBrightnessManual]: DeviceFloodlightLightSettingsBrightnessManualProperty,
    },
    stationProperties: {
        ...BaseStationProperties,
        [PropertyName.StationLANIpAddress]: StationLanIpAddressStandaloneProperty,
        [PropertyName.StationMacAddress]: StationMacAddressProperty,
        [PropertyName.StationGuardMode]: StationGuardModeProperty,
        [PropertyName.StationCurrentMode]: StationCurrentModeProperty,
        [PropertyName.StationTimeFormat]: StationTimeFormatProperty,
        [PropertyName.StationAlarm]: StationAlarmProperty,
        [PropertyName.StationAlarmType]: StationAlarmTypeProperty,
        [PropertyName.StationNotificationSwitchModeSchedule]: StationNotificationSwitchModeScheduleProperty,
        [PropertyName.StationNotificationSwitchModeApp]: StationNotificationSwitchModeAppProperty,
        [PropertyName.StationSdStatus]: StationSdStatusProperty,
        [PropertyName.StationSdCapacity]: StationSdCapacityProperty,
        [PropertyName.StationSdCapacityAvailable]: StationSdAvailableCapacityProperty,
    },
    deviceCommands:[
        CommandName.DeviceStartLivestream,
        CommandName.DeviceStopLivestream,
        CommandName.DeviceStartDownload,
        CommandName.DeviceCancelDownload,
        CommandName.DeviceStartTalkback,
        CommandName.DeviceStopTalkback,
        CommandName.DeviceSnooze,
    ],
    stationCommands: [
        CommandName.StationReboot,
        CommandName.StationTriggerAlarmSound,
        CommandName.StationDownloadImage,
        CommandName.StationDatabaseQueryLatestInfo,
        CommandName.StationDatabaseQueryLocal,
        CommandName.StationDatabaseCountByDate,
        CommandName.StationDatabaseDelete,
    ],
    isSoloCamera:false,
    hasLight: true,
    hasStatusLight: true,
    hasMicrophone: true,
    hasSpeaker: true,
};