name: Question
description: Here you can ask questions
title: '[Question]: '
labels: ['question']
body:
    - type: textarea
      id: question
      attributes:
          label: Ask your question
          description: A clear and concise question
          placeholder: Is it possible to make coffee with this adapter?
      validations:
          required: true
